#ifndef CONFIG_H
#define CONFIG_H

#define SONOSREMOTE_WEBSEVICE "http://sonospebbleremote.appspot.com"
//#define SONOSREMOTE_WEBSEVICE "192.168.1.104:8080"
	
#define SONOSREMOTE_HTTP_COOKIE 726128123
#define SONOSREMOTE_KEY_COMMAND 1 

#define SONOSREMOTE_KEY_PLAY 1
	
#endif // CONFIG_H